"""AUTO_INCREMENT state is not an ordinary column default or an IDENTITY."""
import unittest
from core import auto_increment_contract
from core.shared_column_contract import ordinary_columns

DDL = 'CREATE TABLE g_b_at_autoinc (id INTEGER PRIMARY KEY AUTO_INCREMENT, note INTEGER) AUTO_INCREMENT = 1;'
DROP = 'DROP TABLE g_b_at_autoinc RESTRICT;'
GATES = {'compatibility_mode':['B'], 'case_namespace':['fresh_user_schema'],
         'table_authority':['fixture_table_creator']}


class AutoIncrementContractTests(unittest.TestCase):
    def check(self, value=10, setup=None, gates=None):
        return auto_increment_contract.check_autoincrement_transition(
            f'ALTER TABLE g_b_at_autoinc AUTO_INCREMENT = {value};',
            [DDL] if setup is None else setup, [DROP], GATES if gates is None else gates,
            'g_b_at_autoinc')

    def test_fresh_one_to_ten_and_zero_noop_are_different_models(self):
        a, b = self.check(), self.check(0)
        self.assertTrue(a['requested_value_exceeds_initial'])
        self.assertFalse(b['requested_value_exceeds_initial'])
        self.assertEqual(a['declared_initial'], 1)
        self.assertFalse(a['counter_value_proven'])
        self.assertFalse(a['runtime_proven'])
        self.assertIsNone(ordinary_columns(DDL))

    def test_ordinary_default_identity_or_different_initial_cannot_fake_counter(self):
        for old,new in [('AUTO_INCREMENT,','DEFAULT 1,'),
                        ('AUTO_INCREMENT,','GENERATED BY DEFAULT AS IDENTITY,'),
                        ('AUTO_INCREMENT = 1','AUTO_INCREMENT = 100'),
                        ('id INTEGER','id TEXT')]:
            with self.subTest(new=new), self.assertRaises(ValueError):
                self.check(setup=[DDL.replace(old,new)])

    def test_unknown_prior_writes_or_other_modes_require_separate_contract(self):
        with self.assertRaises(ValueError):
            self.check(setup=[DDL,'INSERT INTO g_b_at_autoinc VALUES (100,1);'])
        for mode in ['A','M','PG']:
            with self.subTest(mode=mode), self.assertRaises(ValueError):
                self.check(gates={**GATES,'compatibility_mode':[mode]})
        for value in [-1,2,2147483648]:
            with self.subTest(value=value), self.assertRaises(ValueError):
                self.check(value)
